---
title: "Week 3 Assignment notebook"
output: html_notebook
---

```{r}
makeVector <- function(x = numeric()) {
        m <- NULL
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
        get <- function() x
        setmean <- function(mean) m <<- mean
        getmean <- function() m
        list(set = set, get = get,
             setmean = setmean,
             getmean = getmean)
}

cachemean <- function(x, ...) {
        m <- x$getmean()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- mean(data, ...)
        x$setmean(m)
        m
}
```

```{r}
a <- c(2,4,6,8)
```

```{r}
b <- makeVector(a)
```

```{r}
print(b)
```

```{r}
b$get()
```

```{r}
b$set()
```

```{r}
b$setmean()
```
```{r}
b$getmean()
```
# run cachemean, since the mean was not calculated, the function will calculate the mean and store it in b

```{r}
cachemean(b)
```

# if you run cacheman again, you can find that the function detected the mean, and returned the message'getting cached data'

```{r}
cachemean(b)
```

